- name: Install SonarQube
  hosts: your_ec2_public_ip
  become: true
  tasks:
    - name: Install OpenJDK
      yum:
        name: java-11-openjdk
        state: present

    - name: Add SonarQube Repository
      yum_repository:
        name: sonarqube
        description: SonarQube Repository
        baseurl: https://binaries.sonarsource.com/Distribution/sonarqube/ sonar-1.0.1.zip
        gpgcheck: no

    - name: Install SonarQube
      yum:
        name: sonarqube
        state: present
